AllCops:
  TargetRubyVersion: 2.6.2
Rails:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/EmptyLines:
  Enabled: false
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 100 
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
